config/routes.rb
Rails.application.routes.draw do
  root to: "articles#index"
  resources :articles do
    member do
      post :notify_friend
    end
    resources :comments
  end
  resources :users
  resource :session
  get "/login", to: "sessions#new", as: "login"
  get "/logout", to: "sessions#destroy", as: "logout"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="header">
      <h1><%= link_to "Blog", root_path %></h1>
      <div id="user_bar">
        <% if logged_in? %>
          <%= link_to "New Article", new_article_path %> |
          <%= link_to "Edit Password", edit_user_path(current_user) %> |
          <%= link_to "Logout", logout_path %>
        <% else %>
          <%= link_to "Login", login_path %>
        <% end %>
      </div>
    </div>
    <div id="main">
      <%= content_tag :p, notice, class: 'notice' if notice.present? %>
      <%= content_tag :p, alert, class: 'alert' if alert.present? %>
      <%= yield %>
    </div>
    <div id="footer">
      A blog for everyone
    </div>  
  </body>
</html>